site_name: piplexed
site_description: Find outdated tools installed with pipx or uv

theme:
  name: 'material'
  palette:
  - media:
    scheme: default
    primary: light blue
    accent: purple
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media:
    scheme: slate
    primary: light blue
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
      - content.code.copy
  icon:
    repo: fontawesome/brands/github
repo_name: aj-white/piplexed
repo_url: https://github.com/aj-white/piplexed
markdown_extensions:
  pymdownx.blocks.admonition:
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True
nav:
  - Home: index.md
  - Installation.md
  - Getting Started: Getting-started.md
  - Command-line-options.md
  - Why-piplexed.md
  - How-piplexed-works.md
  - Future-development.md
  - Release-notes.md

extra_css:
- css/custom.css